### ISSUE TITLE
Merging #1 seems to have broken stuff

### ISSUE THREAD

**Issue by fivetanley** [fivetanley/ember-cli-deploy-fastboot-build#2]
https://ember-api-docs-staging.herokuapp.com/

currently 404s with some revision of the assets that aren't even in the S3 bucket. I think the original code @tomdale wrote rewrote the assets because it got it from the client app, not the fastboot app. The fastboot app is what's being requested from index.html, when it should be the client code.

cc @habdelra

**Comment by habdelra** [comment]
No prob, but when reading from the ember deploy context, let's not read the
context object directly. We should use `this.readConfig('distDir')` instead
of `context.distDir` (same for `fastbootDistDir`), and let's test for the
existence of the
assetMap.json files first. (That's where I was blowing up).
